### ISSUE TITLE
Executing `. gitify.sh` closes shell, no apparent other action

### ISSUE THREAD

**Issue by lkraav** [szepeviktor/gitify#2]
Hi Viktor, how are you.

`./gitify.sh` works:

```
./gitify-zips.sh 
ERROR at command: `test -n "$NAME_PREFIX"`
```

But executing `. gitify.sh` just closes the terminal window. Should it execute exactly the same as `./gitify.sh`

(PS send me an email about what you're working with these days, if you have a few minutes.)

**Comment by szepeviktor** [comment]
Hello @lkraav !

https://github.com/szepeviktor/gitify/blob/master/gitify-zips.sh#L339

gitify needs a name prefix: `./gitify-zips.sh "zip_name_prefix"` to determine what ZIP-s to work on

**Comment by szepeviktor** [comment]
Actually documented in the head: https://github.com/szepeviktor/gitify/blob/master/gitify-zips.sh#L16-L18

**Comment by lkraav** [comment]
Well yes, sure, but shouldn't `. whatever.sh` just give the same result as `./whatever.sh`, instead of abrubtly closing the shell?

You've made some advanced moves I see in the script, and I can't tell whether it's just a side effect of a routine like `trap 'On_exit "$?" "$BASH_COMMAND"' EXIT HUP INT QUIT PIPE TERM`

**Comment by szepeviktor** [comment]
`./script` will open a new process and `exit` in gitify will exit from it.

`. script` is mainly for importing ('source'-ing) configuration, it does **not** open a new process so `exit` will terminate your shell!

https://github.com/szepeviktor/gitify/blob/master/gitify-zips.sh#L281
